name: CI

on:
  push:
    branches:
      - '-DEV/**'
  pull_request:
    branches: [ integration, main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # Si tu proyecto usa Maven (hay pom.xml), compila y prueba
      - name: Build & test (Maven)
        if: ${{ hashFiles('**/pom.xml') != '' }}
        run: mvn -B -q -DskipTests=false verify

      # Si en algún momento decides usar Gradle, este job también funcionará
      - name: Build & test (Gradle)
        if: ${{ hashFiles('**/build.gradle') != '' || hashFiles('**/build.gradle.kts') != '' }}
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build --stacktrace

      - name: Upload surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/target/surefire-reports/**
            **/build/test-results/test/**
            **/build/reports/tests/**
