name: CI

on:
  push:
    branches:
      - '-DEV/**'
  pull_request:
    branches: [ integration, main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build (Maven, skip tests)
        if: ${{ hashFiles('**/pom.xml') != '' }}
        run: mvn -B -q -DskipTests package

      - name: Build (Gradle)
        if: ${{ hashFiles('**/build.gradle') != '' || hashFiles('**/build.gradle.kts') != '' }}
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build --stacktrace -x test

