name: Docker Image

on:
  push:
    branches: [ integration, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ hashFiles('**/Dockerfile') != '' }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/moviehub-backend
          docker build -t $IMAGE:${{ github.sha }} .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
      - name: Push (branch tag)
        run: |
          docker tag $IMAGE:${{ github.sha }} $IMAGE:${{ github.ref_name }}
          docker push $IMAGE:${{ github.ref_name }}
      - name: Push (sha tag)
        run: docker push $IMAGE:${{ github.sha }}
